services:
  anime-service:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "uv", "run", "python", "scripts/healthcheck.py"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8088:8000"
      - "8089:8001"
