services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: anime-backend
    environment:
      - TVDB__API_KEY=${TVDB__API_KEY}
      - TMDB__API_KEY=${TMDB__API_KEY}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
    ports:
      - "9000:9000"
    restart: unless-stopped
